server:
  port: 8080

spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/backend
    username: sa
    password:
    driver-class-name: org.h2.Driver
  h2:
    console:
      enabled: true
  jpa:
    properties:
      hibernate:
        ddl-auto: create
        show-sql: true
        format-sql: true

logging.level:
  org.hibernate.SQL: debug

